name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt
      - run: cargo test
      - name: rustfmt
        run: |
          cargo fmt
          if [[ -n $(git status -s) ]] ; then
            echo "Running rustfmt leaves codebase in modified state."
            echo "Please run rustfmt or cargo fmt on your PR"
            git status -s
            git diff
            exit 1
          fi

  nightly:
    name: Rust nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: cargo test
      - run: cargo update -Z minimal-versions
      - run: cargo build

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: cargo outdated --exit-code 1
